#preload = /home/ben/Wallpapers/planet2.jpg
#preload = /home/ben/Wallpapers/planet3.jpg
#wallpaper = HDMI-A-1, /home/ben/Wallpapers/planet2.jpg
#wallpaper = HDMI-A-2, /home/ben/Wallpapers/planet3.jpg
splash = false
#$directory = /home/ben/Wallpapers/
wallpaper {
    monitor = 
    path = /home/ben/Wallpapers/
    fit_mode = cover
    timeout = 400
}

#wallpaper {
    monitor = HDMI-A-2
    path = $directory
    fit_mode = cover
    timeout = 15
#}